### PR TITLE
Pass some custom header.

### PR DESCRIPTION
**Pull request by trofim24**
Pass some custom header.

### CODE REVIEW

**Comment by brycekahle** [comment]
What proxy is setting those headers?

**Comment by trofim24** [comment]
> What proxy is setting those headers?

These headers are used in conjunction with [Amazon Elastic Load Balancing](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html)

**Comment by brycekahle** [comment]
I do not see `x-forwarded-host` in that documentation. We already allow `x-forwarded-for` and `x-forwarded-proto`.

**Comment by trofim24** [comment]
[Apache Module](http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#x-headers) for `x-forwarded-host`
[Amazon Elastic Load Balancing](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html) for `x-forwarded-port`

If you use a front-end service like Amazon, Apigee or other as the front-end to your APIs, you will need something like `x-forwarded-host` to understand what hostname was used to connect to the API, because Apigee gets configured with whatever your backend DNS is, nginx and your app stack only see the Host header as your backend DNS name, not the hostname that was called in the first place.
`X-Forwarded-Port` gives the port the client connected to on the proxy (e.g. `80` or `443`)

**Comment by agolybev** [comment]
Hi @brycekahle, what about accept pull request?

**Pull request merged**
